[project]
name = "olinkqc"

[dependencies]
arrow = "*"
cowplot = "*"
dbscan = "*"
dplyr = "*"
flextable = "*"
fs = "*"
ggplot2 = "*"
ggrepel = "*"
glue = "*"
here = "*"
janitor = "*"
magrittr = "*"
pathviewr = "*"
purrr = "*"
quarto = "*"
readr = "*"
readxl = "*"
rlang = "*"
rmarkdown = "*"
roxygen2 = "*"
stringr = "*"
tidyr = "*"
tidyselect = "*"
uwot = "*"
