[project]
name = "olinkqc"
r_version = "4.6.1"

[dependencies]
airway = "*"
arrow = "*"
biocthis = "*"
cowplot = "*"
dbscan = "*"
devtools = "*"
dplyr = "*"
flextable = "*"
fs = "*"
gert = "*"
ggplot2 = "*"
ggrepel = "*"
gitcreds = "*"
glue = "*"
here = "*"
janitor = "*"
lobstr = "*"
magrittr = "*"
pak = "*"
pathviewr = "*"
purrr = "*"
quarto = "*"
readr = "*"
readxl = "*"
rlang = "*"
rmarkdown = "*"
roxygen2 = "*"
sloop = "*"
stringr = "*"
tidyr = "*"
tidyselect = "*"
tidyverse = "*"
usethis = "*"
uwot = "*"

[dependencies.SummarizedExperiment]
bioc = true
